from __future__ import annotations

from typing import Any

FIXTURE: list[dict[str, Any]] = [
    {"id": "chat-01", "task": "chat", "hardness": "easy", "prompt": "Hello, what can Rivet do in one sentence?"},
    {"id": "chat-02", "task": "chat", "hardness": "easy", "prompt": "Thanks. Summarize that even shorter."},
    {"id": "chat-03", "task": "chat", "hardness": "easy", "prompt": "What is 2 + 2?"},
    {"id": "chat-04", "task": "chat", "hardness": "easy", "prompt": "Good morning. How should I set OPENAI_BASE_URL?"},
    {"id": "chat-05", "task": "chat", "hardness": "easy", "prompt": "Who pays for tokens when I call Rivet?"},
    {"id": "chat-06", "task": "chat", "hardness": "easy", "prompt": "Remind me: is rivet_usd ever nonzero on BYO workers?"},
    {"id": "chat-07", "task": "chat", "hardness": "easy", "prompt": "Name the four classifier slots."},
    {"id": "chat-08", "task": "chat", "hardness": "easy", "prompt": "What does model auto mean?"},
    {"id": "chat-09", "task": "chat", "hardness": "easy", "prompt": "Give me a curl example for /v1/chat/completions."},
    {"id": "chat-10", "task": "chat", "hardness": "easy", "prompt": "Is streaming supported in this MVP?"},
    {"id": "code-01", "task": "code", "hardness": "easy", "prompt": "Write a Python function that returns the SHA-256 of a string."},
    {"id": "code-02", "task": "code", "hardness": "easy", "prompt": "Fix this TypeScript: const x: number = '1'"},
    {"id": "code-03", "task": "code", "hardness": "easy", "prompt": "Show a FastAPI health endpoint."},
    {"id": "code-04", "task": "code", "hardness": "easy", "prompt": "Write a sqlite CREATE TABLE for a receipt id and vendor_usd."},
    {"id": "code-05", "task": "code", "hardness": "easy", "prompt": "Convert this curl to Python httpx: POST /v1/chat/completions."},
    {"id": "code-06", "task": "code", "hardness": "easy", "prompt": "Write a regex with word boundaries for the phrase code review."},
    {"id": "code-07", "task": "code", "hardness": "easy", "prompt": "Add type hints to def add(a, b): return a + b"},
    {"id": "code-08", "task": "code", "hardness": "easy", "prompt": "Write a pytest that asserts rivet_usd == 0."},
    {"id": "code-09", "task": "code", "hardness": "hard", "prompt": "Please do a code review of this PR that adds a FastAPI proxy."},
    {"id": "code-10", "task": "code", "hardness": "hard", "prompt": "Refactor this module into router, ledger, and workers without breaking tests."},
    {"id": "code-11", "task": "code", "hardness": "hard", "prompt": "Design the architecture for a token ledger that can reopen last month's clusters."},
    {"id": "code-12", "task": "code", "hardness": "hard", "prompt": "Prove that the cheap-first cascade never exceeds max_usd when typical costs are known."},
    {"id": "code-13", "task": "code", "hardness": "hard", "prompt": "Multi-step: parse a stack trace, find the bug, and patch the function."},
    {"id": "code-14", "task": "code", "hardness": "easy", "prompt": "Improve the README so the quick start is three commands."},
    {"id": "prose-01", "task": "prose", "hardness": "easy", "prompt": "Write a 2-line status update for the Rivet MVP. Keep it dry."},
    {"id": "prose-02", "task": "prose", "hardness": "easy", "prompt": "Draft a short paragraph explaining BYO providers versus a marketplace."},
    {"id": "prose-03", "task": "prose", "hardness": "easy", "prompt": "Write a changelog blurb for exact-match cache hits."},
    {"id": "prose-04", "task": "prose", "hardness": "easy", "prompt": "Draft an issue template asking for the first live provider to wire."},
    {"id": "prose-05", "task": "prose", "hardness": "easy", "prompt": "Write a one-sentence positioning line against OpenRouter."},
    {"id": "prose-06", "task": "prose", "hardness": "easy", "prompt": "Blog intro: receipts as the product, not the proxy."},
    {"id": "prose-07", "task": "prose", "hardness": "easy", "prompt": "Write a warning that this demo must not receive production keys in issues."},
    {"id": "prose-08", "task": "prose", "hardness": "easy", "prompt": "Draft a commit message for adding SQLite ledger reopen."},
    {"id": "extract-01", "task": "extract", "hardness": "easy", "prompt": "Extract JSON fields model_used, vendor_usd, rivet_usd from a receipt."},
    {"id": "extract-02", "task": "extract", "hardness": "easy", "prompt": "Parse this table into CSV: model, tokens, usd."},
    {"id": "extract-03", "task": "extract", "hardness": "easy", "prompt": "Extract the schema keys from {id, created_at, cluster, vendor_usd}."},
    {"id": "extract-04", "task": "extract", "hardness": "easy", "prompt": "From this log line, parse latency_ms and cache_hit."},
    {"id": "extract-05", "task": "extract", "hardness": "easy", "prompt": "Turn this receipt into a flat JSON object with no nesting except classifier."},
    {"id": "extract-06", "task": "extract", "hardness": "easy", "prompt": "Extract task labels that are allowed: code prose extract tool chat."},
    {"id": "extract-07", "task": "extract", "hardness": "easy", "prompt": "Parse max_usd from the header X-Rivet-Max-Usd: 0.02"},
    {"id": "extract-08", "task": "extract", "hardness": "easy", "prompt": "List unique providers in: demo, openai, local, demo, openai."},
    {"id": "tool-01", "task": "tool", "hardness": "easy", "prompt": "Propose a tool call to GET /v1/ledger?limit=20"},
    {"id": "tool-02", "task": "tool", "hardness": "easy", "prompt": "Describe an HTTP GET webhook Rivet could ignore on purpose."},
    {"id": "tool-03", "task": "tool", "hardness": "easy", "prompt": "Function call shape to export ledger CSV."},
    {"id": "tool-04", "task": "tool", "hardness": "easy", "prompt": "How would an agent pass rivet.slot=none on a tool-backed completion?"},
    {"id": "tool-05", "task": "tool", "hardness": "easy", "prompt": "Sketch a tool that reads one receipt by id."},
    {"id": "tool-06", "task": "tool", "hardness": "easy", "prompt": "API request: POST /v1/eval/compare with slots rules and none."},
    {"id": "hard-01", "task": "prose", "hardness": "hard", "prompt": "Write a legal opinion on whether a token proxy is a merchant of record."},
    {"id": "hard-02", "task": "code", "hardness": "hard", "prompt": "Code review this authentication middleware for API key timing leaks."},
    {"id": "hard-03", "task": "chat", "hardness": "easy", "prompt": "Can you improve this sentence: Rivet is a switchboard."},
    {"id": "hard-04", "task": "chat", "hardness": "easy", "prompt": "Is storing PII in the ledger prompt column allowed under HIPAA?"},
]


def fixture(limit: int = 50) -> list[dict[str, Any]]:
    return FIXTURE[: max(0, min(limit, len(FIXTURE)))]
